// <auto-generated />
namespace SP_ASPNET_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class blogchange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blogchange));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091056336_blogchange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
